apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weather-app-ingress
  namespace: backend-services
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:650089658128:certificate/038015c7-d29a-4891-84dc-25f8493b7529
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/group.name: "shared-alb"
    alb.ingress.kubernetes.io/healthcheck-path: "/health"
    alb.ingress.kubernetes.io/healthcheck-port: "80"
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "15"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
    alb.ingress.kubernetes.io/success-codes: "200"
spec:
  ingressClassName: alb
  rules:
  - host: weather.captianjack.tech
    http:
      paths:
      - path: /weather
        pathType: Prefix
        backend:
          service:
            name: getweatherservice-service
            port:
              number: 80
      - path: /recommendations
        pathType: Prefix
        backend:
          service:
            name: recomendation-service-service
            port:
              number: 80
      - path: /database
        pathType: Prefix
        backend:
          service:
            name: dbope-service-service
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: getweatherservice-service  # Default route
            port:
              number: 80
