apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: envforrecommendation
  namespace: backend-services
spec:
  refreshInterval: 1s
  secretStoreRef:
    name: secretstore-sample
    kind: ClusterSecretStore
  target:
    name: envforrecommendation
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: backend/recommendation
