apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbope-service
  namespace: backend-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbope-service
  template:
    metadata:
      labels:
        app: dbope-service
    spec:
      containers:
      - name: dbope-service
        image: 279707218273.dkr.ecr.ap-south-1.amazonaws.com/backend3  # Replaced by sed in pipeline
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        volumeMounts:
        - name: env-volume
          mountPath: /app/.env
          subPath: .env
      volumes:
      - name: env-volume
        secret:
          secretName: envfordbope-service

